import textwrap
from fpdf import FPDF

class PDFReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(99, 102, 241)
        self.cell(0, 10, 'IMED Placement Intelligence - Executive ATS Report', 0, new_x="LMARGIN", new_y="NEXT", align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Generated by IMED Career Cell Platform | Page {self.page_no()}', 0, align='C')

def sanitize_pdf_text(text):
    if not text:
        return "N/A"
    
    text = str(text)
    # Nuke structural breaks
    text = text.replace('\t', ' ').replace('\r', '').replace('\n', ' ')
    
    # Force replace typography
    replacements = {
        '“': '"', '”': '"', '‘': "'", '’': "'", 
        '—': '-', '–': '-', '\u2022': '-', '\u2013': '-', '\u2014': '-', '…': '...'
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
        
    # Enforce absolute ASCII compliance
    text = text.encode('ascii', 'ignore').decode('ascii')
    return text

def create_pdf_report(result, resume_name):
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # THE KILL SHOT: Custom Text Wrapper bypassing multi_cell completely
    def write_safe_text(text, is_bold=False, size=10):
        pdf.set_font('Helvetica', 'B' if is_bold else '', size)
        clean_text = sanitize_pdf_text(text)
        
        # Python forces the break at 85 chars. FPDF does no math.
        lines = textwrap.wrap(clean_text, width=85, break_long_words=True)
        
        if not lines:
            lines = [" "]
            
        for line in lines:
            # We use standard cell() which just prints the pre-cut line and moves down
            pdf.cell(0, 6, line, new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(50, 50, 50)
    
    write_safe_text(f'Candidate Resume: {resume_name}', is_bold=True, size=12)
    write_safe_text(f'ATS Match Score: {result.get("match_score", 0)}%', is_bold=True, size=12)
    write_safe_text(f'Readability Index: {result.get("ats_readability", 0)}%', is_bold=True, size=12)
    pdf.ln(5)
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, 'Executive Recruiter Verdict:', new_x="LMARGIN", new_y="NEXT")
    write_safe_text(result.get('recruiter_verdict', ''))
    pdf.ln(5)
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, 'Strategic Action Plan:', new_x="LMARGIN", new_y="NEXT")
    for idx, step in enumerate(result.get('action_plan', []), 1):
        write_safe_text(f"{idx}. {step}")
    pdf.ln(5)
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, 'Optimized Resume Bullet Suggestions:', new_x="LMARGIN", new_y="NEXT")
    for bullet in result.get('optimized_bullets', []):
        write_safe_text(f"- {bullet}")
    pdf.ln(5)
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, 'Targeted Interview Questions:', new_x="LMARGIN", new_y="NEXT")
    for idx, q in enumerate(result.get('interview_questions', []), 1):
        write_safe_text(f"Q{idx}: {q}")
        
    return bytes(pdf.output())