from fpdf import FPDF

class PDFReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(99, 102, 241)
        self.cell(0, 10, 'IMED Placement Intelligence - Executive ATS Report', 0, new_x="LMARGIN", new_y="NEXT", align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Generated by IMED Career Cell Platform | Page {self.page_no()}', 0, align='C')

def sanitize_pdf_text(text):
    if not isinstance(text, str):
        return str(text)
    
    # Force-replace unicode characters that crash standard Helvetica
    replacements = {
        '“': '"', '”': '"', '‘': "'", '’': "'", 
        '—': '-', '–': '-', '\u2022': '-', '\u2013': '-', '\u2014': '-'
    }
    for search, replace in replacements.items():
        text = text.replace(search, replace)
        
    # Strip emojis and unsupported glyphs
    text = text.encode('latin-1', 'replace').decode('latin-1')
    
    # Break unbroken strings (like long markdown dividers) so fpdf can wrap them
    words = text.split(' ')
    safe_words = [w if len(w) < 70 else w[:67] + '...' for w in words]
    
    return ' '.join(safe_words)

def create_pdf_report(result, resume_name):
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 8, sanitize_pdf_text(f'Candidate Resume: {resume_name}'), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, sanitize_pdf_text(f'ATS Match Score: {result.get("match_score", 0)}%'), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, sanitize_pdf_text(f'Readability Index: {result.get("ats_readability", 0)}%'), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, 'Executive Recruiter Verdict:', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Helvetica', '', 10)
    pdf.multi_cell(0, 6, sanitize_pdf_text(result.get('recruiter_verdict', '')))
    pdf.ln(5)
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, 'Strategic Action Plan:', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Helvetica', '', 10)
    for idx, step in enumerate(result.get('action_plan', []), 1):
        pdf.multi_cell(0, 6, sanitize_pdf_text(f"{idx}. {step}"))
    pdf.ln(5)
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, 'Optimized Resume Bullet Suggestions:', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Courier', '', 9)
    for bullet in result.get('optimized_bullets', []):
        pdf.multi_cell(0, 6, sanitize_pdf_text(f"- {bullet}"))
        
    return pdf.output()