import re
from fpdf import FPDF

class PDFReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(99, 102, 241)
        self.cell(0, 10, 'IMED Placement Intelligence - Executive ATS Report', 0, new_x="LMARGIN", new_y="NEXT", align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Generated by IMED Career Cell Platform | Page {self.page_no()}', 0, align='C')

def sanitize_pdf_text(text):
    if not text:
        return "N/A"
        
    text = str(text)
    
    # 1. NUKE TABS AND CARRIAGE RETURNS (The #1 cause of this fpdf math crash)
    text = text.replace('\t', '    ').replace('\r', '')
    
    # 2. Replace typography that crashes Helvetica
    replacements = {
        '“': '"', '”': '"', '‘': "'", '’': "'", 
        '—': '-', '–': '-', '\u2022': '-', '\u2013': '-', '\u2014': '-', '…': '...'
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
        
    # 3. STRICT ASCII ENFORCEMENT (Vaporizes emojis and zero-width spaces)
    text = text.encode('ascii', 'ignore').decode('ascii')
    
    # 4. AGGRESSIVE STRING BREAKING (Uses regex to keep newlines but break huge words)
    words = re.split(r'(\s+)', text)
    safe_words = []
    for w in words:
        if len(w) > 65 and not w.isspace():
            safe_words.append(w[:62] + '...')
        else:
            safe_words.append(w)
            
    final_text = "".join(safe_words).strip()
    return final_text if final_text else "N/A"

def create_pdf_report(result, resume_name):
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(50, 50, 50)
    
    # Helper to safely add cells without throwing empty string errors
    def safe_cell(text):
        pdf.cell(0, 8, sanitize_pdf_text(text), new_x="LMARGIN", new_y="NEXT")
        
    safe_cell(f'Candidate Resume: {resume_name}')
    safe_cell(f'ATS Match Score: {result.get("match_score", 0)}%')
    safe_cell(f'Readability Index: {result.get("ats_readability", 0)}%')
    pdf.ln(5)
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, 'Executive Recruiter Verdict:', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Helvetica', '', 10)
    pdf.multi_cell(0, 6, sanitize_pdf_text(result.get('recruiter_verdict', '')))
    pdf.ln(5)
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, 'Strategic Action Plan:', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Helvetica', '', 10)
    for idx, step in enumerate(result.get('action_plan', []), 1):
        pdf.multi_cell(0, 6, sanitize_pdf_text(f"{idx}. {step}"))
    pdf.ln(5)
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, 'Optimized Resume Bullet Suggestions:', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Courier', '', 9)
    for bullet in result.get('optimized_bullets', []):
        pdf.multi_cell(0, 6, sanitize_pdf_text(f"- {bullet}"))
        
    # I also noticed your Interview Questions were missing from the old PDF output. Added them here.
    pdf.ln(5)
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, 'Targeted Interview Questions:', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Helvetica', '', 10)
    for idx, q in enumerate(result.get('interview_questions', []), 1):
        pdf.multi_cell(0, 6, sanitize_pdf_text(f"Q{idx}: {q}"))
        
    return pdf.output()